name: mavunohub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.13.7"

dependencies:
  flutter:
    sdk: flutter
  # firebase_core_platform_interface: 4.4.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  firebase_core_web:
  firebase_auth_web:
  firebase_analytics:
  google_sign_in:
  intl_phone_field: ^3.1.0
  get: ^4.6.6
  cloud_firestore_web: ^3.7.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.14
  flutter_dialogs: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/mavunohub_icon.png"
  
flutter:

  uses-material-design: true

  assets:
    - assets/mavunohub_logo.png       
    - assets/mavunohub_icon.png        
    - assets/mavunomark.png   
    - assets/holding-phone.png   

  fonts:
    - family: Gilmer
      fonts:
        - asset: fonts/Gilmer-Regular.otf
        - asset: fonts/Gilmer-Medium.otf
        - asset: fonts/Gilmer-Heavy.otf
        - asset: fonts/Gilmer-Bold.otf  
 
