  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi1SJ7abwOZzexunwohYlyXVEmluRXtgU',
    appId: '1:914748917180:web:69d19a583a5ae594ddd7b9',
    messagingSenderId: '914748917180',
    projectId: 'mavunohub-37adb',
    authDomain: 'mavunohub-37adb.firebaseapp.com',
    storageBucket: 'mavunohub-37adb.appspot.com',
    measurementId: 'G-QN0EN1P02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDLwMe_bKY0ImJV_sp9DE3ekb8Z6Prp8',
    appId: '1:914748917180:android:5ea0106f94c07f16ddd7b9',
    messagingSenderId: '914748917180',
    projectId: 'mavunohub-37adb',
    storageBucket: 'mavunohub-37adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiOmXA1QTn_l6xthuIcXU1JAoaR30MVfE',
    appId: '1:914748917180:ios:5c999e27034a44fcddd7b9',
    messagingSenderId: '914748917180',
    projectId: 'mavunohub-37adb',
    storageBucket: 'mavunohub-37adb.appspot.com',
    iosBundleId: 'com.example.mavunohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiOmXA1QTn_l6xthuIcXU1JAoaR30MVfE',
    appId: '1:914748917180:ios:423980d15446a31fddd7b9',
    messagingSenderId: '914748917180',
    projectId: 'mavunohub-37adb',
    storageBucket: 'mavunohub-37adb.appspot.com',
    iosBundleId: 'com.example.mavunohub.RunnerTests',
  );
}
